<?php
/**
 * Workshop_Faq extension
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Workshop
 * @package   Workshop_Faq
 * @copyright Copyright (c) 2017
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php /** @var \Workshop\Faq\Block\Faq\ListFaq $block */ ?>
<?php $_faqs = $block->getFaqs(); ?>
<div class="authors">
    <?php if ($_faqs->getSize() > 0) :?>
        <div class="workshop-faq-toolbar toolbar top"><?php echo $block->getPagerHtml(); ?></div>
        <div class="workshop-faq-list-container">
            <?php foreach ($_faqs as $_faq) : ?>
                <?php /** @var \Workshop\Faq\Model\Faq $_faq */ ?>
                <div class="sample-news-author-list-item">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getFaqUrl($_faq); ?>">
                        <?php echo /* @escapeNotVerified */ $_faq->getQuestion();?>
                    </a>
                </div>
            <?php endforeach;?>
        </div>
        <div class="workshop-faq-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php else : ?>
        <?php echo __('There are no FAQs at this moment');?>
    <?php endif;?>
</div>
