<?php
/**
 * Workshop_Faq extension
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Workshop
 * @package   Workshop_Faq
 * @copyright Copyright (c) 2017
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php /** @var \Workshop\Faq\Block\Faq\ViewFaq $block */?>
<?php $_faq = $block->getCurrentFaq();?>
<div class="faq-view">
    <div class="author-name">
        <strong><?php /* @escapeNotVerified */ echo $_faq->getQuestion();?></strong>
    </div>
    <?php if ($answer = $block->getProcessedValue($_faq, 'answer')) :?>
        <div class="faq-answer">
            <strong><?php /* @escapeNotVerified */ echo __('Answer') ?></strong>: <?php /* @escapeNotVerified */ echo $answer;?>
        </div>
    <?php endif;?>
</div>
